apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: collector-psacct
  namespace: exporter
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/benko/ocp-collector-psacct:latest
      importPolicy: {}
      referencePolicy:
        type: Source
