apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: collector-sysstat
  namespace: exporter
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/benko/ocp-collector-sysstat:latest
      importPolicy: {}
      referencePolicy:
        type: Source
