apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - serviceaccount.yml
  - privileged-clusterrolebinding.yml
  - prometheus-role.yml
  - prometheus-rolebinding.yml
  - daemonset.yml
# Rot. ICT don't work with DaemonSets.
#  - is-collector-sysstat.yml
#  - is-collector-psacct.yml
#  - is-metrics-exporter.yml
