apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-scrape
  namespace: exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-scrape
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: prometheus-k8s
  namespace: prometheus
