apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: example
  namespace: prometheus
spec:
  datasources:
    - name: prometheus
      type: prometheus
      url: 'http://prometheus-operated:9090/'
  name: prometheus
