apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: dashboards
  namespace: prometheus
spec:
  config: {}
  dataStorage:
    class: nfs-storage
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  ingress:
    enabled: true
