apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/prometheus.prometheus: ""
  name: prometheus
  namespace: prometheus
spec:
  channel: beta
  installPlanApproval: Automatic
  name: prometheus
  source: redhat-operators-3scale-community
  sourceNamespace: openshift-marketplace
  startingCSV: prometheusoperator.0.47.0
