apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: collector-psacct
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: latest
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: collector-psacct
      labels:
        build: collector-psacct
        build-config: collector-psacct
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: collector-psacct:latest
      source:
        git:
          uri: https://git.p0f.net/gregab/linux-metrics-exporter.git
          ref: main
        contextDir: images
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Containerfile-psacct
          from:
            kind: ImageStreamTag
            name: ubi-minimal:latest
          volumes:
            - source:
                type: Secret
                secret:
                  secretName: etc-pki-entitlement
              name: etc-pki-entitlement
              mounts:
                - destinationPath: /etc/pki/entitlement
            - source:
                type: Secret
                secret:
                  secretName: rhsm-ca
              name: rhsm-ca
              mounts:
                - destinationPath: /etc/rhsm/ca
