FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

#FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

USER 0

COPY entrypoint-psacct.sh /usr/local/bin/entrypoint.sh

RUN microdnf install psacct && \
    rm -rf /var/lib/dnf /var/cache/dnf /var/cache/cups /var/cache/PackageKit && \
    chmod 755 /usr/local/bin/entrypoint.sh

VOLUME /var/account

ARG STARTUP_SCRATCH
ARG CUMULATIVE

LABEL description="Minimal psacct collector sidecar image" \
	io.k8s.description="Minimal psacct collector sidecar image" \
	io.k8s.display-name="psacct collector" \
	io.openshift.expose-services="" \
	maintainer="Grega Bremec <gregab@p0f.net> \
	vendor="P0F" \
	version="v1.0" \
	release="1.0" \
	License=BSD

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

