FROM registry.access.redhat.io/ubi9/ubi-minimal:latest

USER 0

COPY entrypoint-sysstat.sh /usr/local/bin/entrypoint.sh

RUN microdnf install sysstat && \
    rm -rf /var/lib/dnf /var/cache/dnf /var/cache/cups /var/cache/PackageKit && \
    chmod 755 /usr/local/bin/entrypoint.sh

VOLUME /var/log/sa

ARG STARTUP_SCRATCH
ARG STARTUP_ROTATE

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

