apiVersion: builtin
kind: PatchJson6902Transformer
metadata:
  name: fix-namespace-of-the-podmonitor-resource
target:
  group: monitoring.coreos.com
  version: v1
  kind: PodMonitor
  name: exporter-monitor
# Set the project in this file ("value:") to wherever your Prometheus is.
path: fix-podmonitor-namespace.json
